/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1d1 */
package com.meidusa.amoeba.sqljep;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFUNNODE = 2;
  public int JJTVARNODE = 3;
  public int JJTARRAY = 4;
  public int JJTCONSTANT = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "FunNode",
    "VarNode",
    "Array",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=22da27626797a5d3757afdebb5bfe0ec (do not edit this line) */
