/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 4.1d1 */
package com.meidusa.amoeba.sqljep;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data) throws ParseException;
  public Object visit(ASTStart node, Object data) throws ParseException;
  public Object visit(ASTFunNode node, Object data) throws ParseException;
  public Object visit(ASTVarNode node, Object data) throws ParseException;
  public Object visit(ASTArray node, Object data) throws ParseException;
  public Object visit(ASTConstant node, Object data) throws ParseException;
}
/* JavaCC - OriginalChecksum=78049580ff25fabdceb758a89080b84e (do not edit this line) */
