/* Generated By:JavaCC: Do not edit this line. MysqlParserTreeConstants.java Version 5.0 */
package com.meidusa.amoeba.mysql.parser.sql;

public interface MysqlParserTreeConstants
{
  public int JJTVOID = 0;


  public String[] jjtNodeName = {
    "void",
  };
}
/* JavaCC - OriginalChecksum=dfbb97a40f8c7240511d1c243626087a (do not edit this line) */
