/* Generated By:JJTree&JavaCC: Do not edit this line. MysqlParserConstants.java */
/*
 * Copyright (C) 2008 Struct chen <piratebase@sina.com>
 * 	This program is free software; you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, 
 * or (at your option) any later version. 
 * 
 * 	This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
 * See the GNU General Public License for more details. 
 * 	You should have received a copy of the GNU General Public License along with this program; 
 * if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package com.meidusa.amoeba.mysql.parser.sql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MysqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_DONET = 5;
  /** RegularExpression Id. */
  int K_ALL = 6;
  /** RegularExpression Id. */
  int K_AND = 7;
  /** RegularExpression Id. */
  int K_ANY = 8;
  /** RegularExpression Id. */
  int K_AS = 9;
  /** RegularExpression Id. */
  int K_BETWEEN = 10;
  /** RegularExpression Id. */
  int K_BOOLEAN = 11;
  /** RegularExpression Id. */
  int K_BY = 12;
  /** RegularExpression Id. */
  int K_CASE = 13;
  /** RegularExpression Id. */
  int K_CAST = 14;
  /** RegularExpression Id. */
  int K_CHAR = 15;
  /** RegularExpression Id. */
  int K_CHARACTER = 16;
  /** RegularExpression Id. */
  int K_DECIMAL = 17;
  /** RegularExpression Id. */
  int K_DEC = 18;
  /** RegularExpression Id. */
  int K_DELETE = 19;
  /** RegularExpression Id. */
  int K_DISTINCT = 20;
  /** RegularExpression Id. */
  int K_DO = 21;
  /** RegularExpression Id. */
  int K_DOUBLE = 22;
  /** RegularExpression Id. */
  int K_DROP = 23;
  /** RegularExpression Id. */
  int K_ELSE = 24;
  /** RegularExpression Id. */
  int K_ELSEIF = 25;
  /** RegularExpression Id. */
  int K_END = 26;
  /** RegularExpression Id. */
  int K_ESCAPE = 27;
  /** RegularExpression Id. */
  int K_EXISTS = 28;
  /** RegularExpression Id. */
  int K_FETCH = 29;
  /** RegularExpression Id. */
  int K_FLOAT = 30;
  /** RegularExpression Id. */
  int K_FOR = 31;
  /** RegularExpression Id. */
  int K_FROM = 32;
  /** RegularExpression Id. */
  int K_FULL = 33;
  /** RegularExpression Id. */
  int K_GROUP = 34;
  /** RegularExpression Id. */
  int K_HAVING = 35;
  /** RegularExpression Id. */
  int K_IN = 36;
  /** RegularExpression Id. */
  int K_IS = 37;
  /** RegularExpression Id. */
  int K_INTO = 38;
  /** RegularExpression Id. */
  int K_INDEX = 39;
  /** RegularExpression Id. */
  int K_INNER = 40;
  /** RegularExpression Id. */
  int K_INSERT = 41;
  /** RegularExpression Id. */
  int K_REPLACE = 42;
  /** RegularExpression Id. */
  int K_INTEGER = 43;
  /** RegularExpression Id. */
  int K_INT = 44;
  /** RegularExpression Id. */
  int K_JOIN = 45;
  /** RegularExpression Id. */
  int K_LEFT = 46;
  /** RegularExpression Id. */
  int K_NATURAL = 47;
  /** RegularExpression Id. */
  int K_CROSS = 48;
  /** RegularExpression Id. */
  int K_LIKE = 49;
  /** RegularExpression Id. */
  int K_LOCK = 50;
  /** RegularExpression Id. */
  int K_LOOP = 51;
  /** RegularExpression Id. */
  int K_CREATE = 52;
  /** RegularExpression Id. */
  int K_NOT = 53;
  /** RegularExpression Id. */
  int K_NOT2 = 54;
  /** RegularExpression Id. */
  int K_NULL = 55;
  /** RegularExpression Id. */
  int K_NULLS = 56;
  /** RegularExpression Id. */
  int K_NUMBER = 57;
  /** RegularExpression Id. */
  int K_NUMERIC = 58;
  /** RegularExpression Id. */
  int K_OF = 59;
  /** RegularExpression Id. */
  int K_ON = 60;
  /** RegularExpression Id. */
  int K_NOWAIT = 61;
  /** RegularExpression Id. */
  int K_ONLY = 62;
  /** RegularExpression Id. */
  int K_OR = 63;
  /** RegularExpression Id. */
  int K_OR2 = 64;
  /** RegularExpression Id. */
  int K_ORDER = 65;
  /** RegularExpression Id. */
  int K_OUTER = 66;
  /** RegularExpression Id. */
  int K_QUERYNO = 67;
  /** RegularExpression Id. */
  int K_OPTIMIZE = 68;
  /** RegularExpression Id. */
  int K_READ = 69;
  /** RegularExpression Id. */
  int K_REAL = 70;
  /** RegularExpression Id. */
  int K_OPTION = 71;
  /** RegularExpression Id. */
  int K_OFFSET = 72;
  /** RegularExpression Id. */
  int K_EXPLAIN = 73;
  /** RegularExpression Id. */
  int K_EXTENDED = 74;
  /** RegularExpression Id. */
  int K_SELECT = 75;
  /** RegularExpression Id. */
  int K_SET = 76;
  /** RegularExpression Id. */
  int K_XA = 77;
  /** RegularExpression Id. */
  int K_SOME = 78;
  /** RegularExpression Id. */
  int K_TABLE = 79;
  /** RegularExpression Id. */
  int K_SHOW = 80;
  /** RegularExpression Id. */
  int K_MOD = 81;
  /** RegularExpression Id. */
  int K_DIV = 82;
  /** RegularExpression Id. */
  int K_THEN = 83;
  /** RegularExpression Id. */
  int K_TO = 84;
  /** RegularExpression Id. */
  int K_UNION = 85;
  /** RegularExpression Id. */
  int K_UNIQUE = 86;
  /** RegularExpression Id. */
  int K_UPDATE = 87;
  /** RegularExpression Id. */
  int K_USE = 88;
  /** RegularExpression Id. */
  int K_USING = 89;
  /** RegularExpression Id. */
  int K_VALUES = 90;
  /** RegularExpression Id. */
  int K_VARCHAR2 = 91;
  /** RegularExpression Id. */
  int K_VARCHAR = 92;
  /** RegularExpression Id. */
  int K_WHEN = 93;
  /** RegularExpression Id. */
  int K_WHERE = 94;
  /** RegularExpression Id. */
  int K_WHILE = 95;
  /** RegularExpression Id. */
  int K_WITH = 96;
  /** RegularExpression Id. */
  int K_TRUE = 97;
  /** RegularExpression Id. */
  int K_FALSE = 98;
  /** RegularExpression Id. */
  int K_LIMIT = 99;
  /** RegularExpression Id. */
  int K_RIGHT = 100;
  /** RegularExpression Id. */
  int K_INTERVAL = 101;
  /** RegularExpression Id. */
  int K_YEAR = 102;
  /** RegularExpression Id. */
  int K_MICROSECOND = 103;
  /** RegularExpression Id. */
  int K_SECOND = 104;
  /** RegularExpression Id. */
  int K_DAY = 105;
  /** RegularExpression Id. */
  int K_MINUTE = 106;
  /** RegularExpression Id. */
  int K_MONTH = 107;
  /** RegularExpression Id. */
  int K_HOUR = 108;
  /** RegularExpression Id. */
  int K_COMMIT = 109;
  /** RegularExpression Id. */
  int K_BEGIN = 110;
  /** RegularExpression Id. */
  int K_ROLLBACK = 111;
  /** RegularExpression Id. */
  int K_DESC = 112;
  /** RegularExpression Id. */
  int K_ASC = 113;
  /** RegularExpression Id. */
  int K_IGNORE_INDEX = 114;
  /** RegularExpression Id. */
  int K_FORCE_INDEX = 115;
  /** RegularExpression Id. */
  int K_TRANSACTION_ISOLATION_LEVEL = 116;
  /** RegularExpression Id. */
  int K_DUPLICATE = 117;
  /** RegularExpression Id. */
  int K_KEY = 118;
  /** RegularExpression Id. */
  int K_KEYS = 119;
  /** RegularExpression Id. */
  int K_START_TRANSACTION = 120;
  /** RegularExpression Id. */
  int K_SESSION = 121;
  /** RegularExpression Id. */
  int K_TRANSACTION_READ_COMMITTED = 122;
  /** RegularExpression Id. */
  int K_TRANSACTION_READ_UNCOMMITTED = 123;
  /** RegularExpression Id. */
  int K_TRANSACTION_REPEATABLE_READ = 124;
  /** RegularExpression Id. */
  int K_TRANSACTION_SERIALIZABLE = 125;
  /** RegularExpression Id. */
  int K_CLIENT_CHARSET = 126;
  /** RegularExpression Id. */
  int K_SHOW_FULL_TABLES = 127;
  /** RegularExpression Id. */
  int K_SHOW_OPEN_TABLES = 128;
  /** RegularExpression Id. */
  int K_SHOW_CREATE_PROCEDURE = 129;
  /** RegularExpression Id. */
  int K_SHOW_CREATE_DATABASE = 130;
  /** RegularExpression Id. */
  int K_SHOW_FULL_COLUMNS = 131;
  /** RegularExpression Id. */
  int K_TABLE_STATUS = 132;
  /** RegularExpression Id. */
  int K_VARIABLES = 133;
  /** RegularExpression Id. */
  int K_GRANTS_FOR = 134;
  /** RegularExpression Id. */
  int K_TRIGGERS = 135;
  /** RegularExpression Id. */
  int K_PROCEDURE = 136;
  /** RegularExpression Id. */
  int K_EVENTS = 137;
  /** RegularExpression Id. */
  int K_CALL = 138;
  /** RegularExpression Id. */
  int K_CHARACTER_SET = 139;
  /** RegularExpression Id. */
  int K_IF_NOT_EXISTS = 140;
  /** RegularExpression Id. */
  int K_IF_EXISTS = 141;
  /** RegularExpression Id. */
  int K_PRIMARY = 142;
  /** RegularExpression Id. */
  int K_TRUNCATE = 143;
  /** RegularExpression Id. */
  int K_VIEW = 144;
  /** RegularExpression Id. */
  int K_DATABASE = 145;
  /** RegularExpression Id. */
  int K_SEQUENCE = 146;
  /** RegularExpression Id. */
  int K_TRIGGER = 147;
  /** RegularExpression Id. */
  int K_FUNCTION = 148;
  /** RegularExpression Id. */
  int K_TEMPORARY = 149;
  /** RegularExpression Id. */
  int K_GLOBAL = 150;
  /** RegularExpression Id. */
  int K_LOCAL = 151;
  /** RegularExpression Id. */
  int K_RENAME = 152;
  /** RegularExpression Id. */
  int K_ALTER = 153;
  /** RegularExpression Id. */
  int K_IGNORE = 154;
  /** RegularExpression Id. */
  int K_HELP = 155;
  /** RegularExpression Id. */
  int K_DISTINCTROW = 156;
  /** RegularExpression Id. */
  int K_HIGH_PRIORITY = 157;
  /** RegularExpression Id. */
  int K_STRAIGHT_JOIN = 158;
  /** RegularExpression Id. */
  int K_SQL_SMALL_RESULT = 159;
  /** RegularExpression Id. */
  int K_SQL_BIG_RESULT = 160;
  /** RegularExpression Id. */
  int K_SQL_BUFFER_RESULT = 161;
  /** RegularExpression Id. */
  int K_SQL_CACHE = 162;
  /** RegularExpression Id. */
  int K_SQL_NO_CACHE = 163;
  /** RegularExpression Id. */
  int K_SQL_CALC_FOUND_ROWS = 164;
  /** RegularExpression Id. */
  int K_ACCESSIBLE = 165;
  /** RegularExpression Id. */
  int K_BEFORE = 166;
  /** RegularExpression Id. */
  int K_BINARY = 167;
  /** RegularExpression Id. */
  int K_COLUMN = 168;
  /** RegularExpression Id. */
  int K_CONTINUE = 169;
  /** RegularExpression Id. */
  int K_CURRENT_TIMESTAMP = 170;
  /** RegularExpression Id. */
  int K_DAY_MICROSECOND = 171;
  /** RegularExpression Id. */
  int K_DEFAULT = 172;
  /** RegularExpression Id. */
  int K_EACH = 173;
  /** RegularExpression Id. */
  int K_ENCLOSED = 174;
  /** RegularExpression Id. */
  int K_EXIT = 175;
  /** RegularExpression Id. */
  int K_FLOAT8 = 176;
  /** RegularExpression Id. */
  int K_FOREIGN = 177;
  /** RegularExpression Id. */
  int K_GRANT = 178;
  /** RegularExpression Id. */
  int K_HOUR_SECOND = 179;
  /** RegularExpression Id. */
  int K_INT2 = 180;
  /** RegularExpression Id. */
  int K_INT8 = 181;
  /** RegularExpression Id. */
  int K_KILL = 182;
  /** RegularExpression Id. */
  int K_LINEAR = 183;
  /** RegularExpression Id. */
  int K_LOCALTIME = 184;
  /** RegularExpression Id. */
  int K_LONG = 185;
  /** RegularExpression Id. */
  int K_MATCH = 186;
  /** RegularExpression Id. */
  int K_MEDIUMINT = 187;
  /** RegularExpression Id. */
  int K_MINUTE_MICROSECOND = 188;
  /** RegularExpression Id. */
  int K_MODIFIES = 189;
  /** RegularExpression Id. */
  int K_NO_WRITE_TO_BINLOG = 190;
  /** RegularExpression Id. */
  int K_OPTIONALLY = 191;
  /** RegularExpression Id. */
  int K_OUT = 192;
  /** RegularExpression Id. */
  int K_PRECISION = 193;
  /** RegularExpression Id. */
  int K_PURGE = 194;
  /** RegularExpression Id. */
  int K_READS = 195;
  /** RegularExpression Id. */
  int K_REFERENCES = 196;
  /** RegularExpression Id. */
  int K_REQUIRE = 197;
  /** RegularExpression Id. */
  int K_RETURN = 198;
  /** RegularExpression Id. */
  int K_RLIKE = 199;
  /** RegularExpression Id. */
  int K_SECOND_MICROSECOND = 200;
  /** RegularExpression Id. */
  int K_SEPARATOR = 201;
  /** RegularExpression Id. */
  int K_SIGNAL = 202;
  /** RegularExpression Id. */
  int K_SPECIFIC = 203;
  /** RegularExpression Id. */
  int K_SQLSTATE = 204;
  /** RegularExpression Id. */
  int K_STARTING = 205;
  /** RegularExpression Id. */
  int K_TERMINATED = 206;
  /** RegularExpression Id. */
  int K_TINYINT = 207;
  /** RegularExpression Id. */
  int K_TRAILING = 208;
  /** RegularExpression Id. */
  int K_UNDO = 209;
  /** RegularExpression Id. */
  int K_UNLOCK = 210;
  /** RegularExpression Id. */
  int K_USAGE = 211;
  /** RegularExpression Id. */
  int K_UTC_DATE = 212;
  /** RegularExpression Id. */
  int K_VARCHARACTER = 213;
  /** RegularExpression Id. */
  int K_WRITE = 214;
  /** RegularExpression Id. */
  int K_ZEROFILL = 215;
  /** RegularExpression Id. */
  int K_ADD = 216;
  /** RegularExpression Id. */
  int K_ANALYZE = 217;
  /** RegularExpression Id. */
  int K_BLOB = 218;
  /** RegularExpression Id. */
  int K_CHANGE = 219;
  /** RegularExpression Id. */
  int K_CHECK = 220;
  /** RegularExpression Id. */
  int K_CONDITION = 221;
  /** RegularExpression Id. */
  int K_CONVERT = 222;
  /** RegularExpression Id. */
  int K_CURRENT_DATE = 223;
  /** RegularExpression Id. */
  int K_CURRENT_USER = 224;
  /** RegularExpression Id. */
  int K_DATABASES = 225;
  /** RegularExpression Id. */
  int K_DAY_MINUTE = 226;
  /** RegularExpression Id. */
  int K_DELAYED = 227;
  /** RegularExpression Id. */
  int K_ESCAPED = 228;
  /** RegularExpression Id. */
  int K_HOUR_MICROSECOND = 229;
  /** RegularExpression Id. */
  int K_IF = 230;
  /** RegularExpression Id. */
  int K_INOUT = 231;
  /** RegularExpression Id. */
  int K_INT3 = 232;
  /** RegularExpression Id. */
  int K_LEADING = 233;
  /** RegularExpression Id. */
  int K_LINES = 234;
  /** RegularExpression Id. */
  int K_LOCALTIMESTAMP = 235;
  /** RegularExpression Id. */
  int K_LONGBLOB = 236;
  /** RegularExpression Id. */
  int K_LOW_PRIORITY = 237;
  /** RegularExpression Id. */
  int K_MAXVALUE = 238;
  /** RegularExpression Id. */
  int K_MEDIUMTEXT = 239;
  /** RegularExpression Id. */
  int K_MINUTE_SECOND = 240;
  /** RegularExpression Id. */
  int K_RANGE = 241;
  /** RegularExpression Id. */
  int K_READ_WRITE = 242;
  /** RegularExpression Id. */
  int K_REGEXP = 243;
  /** RegularExpression Id. */
  int K_REPEAT = 244;
  /** RegularExpression Id. */
  int K_RESIGNAL = 245;
  /** RegularExpression Id. */
  int K_REVOKE = 246;
  /** RegularExpression Id. */
  int K_SMALLINT = 247;
  /** RegularExpression Id. */
  int K_SQL = 248;
  /** RegularExpression Id. */
  int K_SQLWARNING = 249;
  /** RegularExpression Id. */
  int K_TINYTEXT = 250;
  /** RegularExpression Id. */
  int K_UNSIGNED = 251;
  /** RegularExpression Id. */
  int K_UTC_TIME = 252;
  /** RegularExpression Id. */
  int K_VARBINARY = 253;
  /** RegularExpression Id. */
  int K_VARYING = 254;
  /** RegularExpression Id. */
  int K_XOR = 255;
  /** RegularExpression Id. */
  int K_ASENSITIVE = 256;
  /** RegularExpression Id. */
  int K_BIGINT = 257;
  /** RegularExpression Id. */
  int K_BOTH = 258;
  /** RegularExpression Id. */
  int K_CASCADE = 259;
  /** RegularExpression Id. */
  int K_COLLATE = 260;
  /** RegularExpression Id. */
  int K_CONSTRAINT = 261;
  /** RegularExpression Id. */
  int K_CURRENT_TIME = 262;
  /** RegularExpression Id. */
  int K_CURSOR = 263;
  /** RegularExpression Id. */
  int K_DAY_HOUR = 264;
  /** RegularExpression Id. */
  int K_DAY_SECOND = 265;
  /** RegularExpression Id. */
  int K_DECLARE = 266;
  /** RegularExpression Id. */
  int K_DETERMINISTIC = 267;
  /** RegularExpression Id. */
  int K_DUAL = 268;
  /** RegularExpression Id. */
  int K_FLOAT4 = 269;
  /** RegularExpression Id. */
  int K_FORCE = 270;
  /** RegularExpression Id. */
  int K_FULLTEXT = 271;
  /** RegularExpression Id. */
  int K_HOUR_MINUTE = 272;
  /** RegularExpression Id. */
  int K_INFILE = 273;
  /** RegularExpression Id. */
  int K_INSENSITIVE = 274;
  /** RegularExpression Id. */
  int K_INT1 = 275;
  /** RegularExpression Id. */
  int K_INT4 = 276;
  /** RegularExpression Id. */
  int K_ITERATE = 277;
  /** RegularExpression Id. */
  int K_LEAVE = 278;
  /** RegularExpression Id. */
  int K_LOAD = 279;
  /** RegularExpression Id. */
  int K_LONGTEXT = 280;
  /** RegularExpression Id. */
  int K_MASTER_SSL_VERIFY_SERVER_CERT = 281;
  /** RegularExpression Id. */
  int K_MEDIUMBLOB = 282;
  /** RegularExpression Id. */
  int K_MIDDLEINT = 283;
  /** RegularExpression Id. */
  int K_OUTFILE = 284;
  /** RegularExpression Id. */
  int K_RELEASE = 285;
  /** RegularExpression Id. */
  int K_RESTRICT = 286;
  /** RegularExpression Id. */
  int K_SCHEMAS = 287;
  /** RegularExpression Id. */
  int K_SENSITIVE = 288;
  /** RegularExpression Id. */
  int K_SPATIAL = 289;
  /** RegularExpression Id. */
  int K_SQLEXCEPTION = 290;
  /** RegularExpression Id. */
  int K_SSL = 291;
  /** RegularExpression Id. */
  int K_TINYBLOB = 292;
  /** RegularExpression Id. */
  int K_UTC_TIMESTAMP = 293;
  /** RegularExpression Id. */
  int K_YEAR_MONTH = 294;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 295;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 296;
  /** RegularExpression Id. */
  int EXPONENT = 297;
  /** RegularExpression Id. */
  int DIGIT = 298;
  /** RegularExpression Id. */
  int LINE_COMMENT = 299;
  /** RegularExpression Id. */
  int IDENTIFIER = 300;
  /** RegularExpression Id. */
  int LETTER = 301;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 302;
  /** RegularExpression Id. */
  int STRING_LITERAL = 303;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 304;
  /** RegularExpression Id. */
  int S_COMMA_IDENTIFIER = 305;
  /** RegularExpression Id. */
  int S_PARAMETER_MARKER = 306;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"@\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"BETWEEN\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CHAR\"",
    "\"CHARACTER\"",
    "\"DECIMAL\"",
    "\"DEC\"",
    "\"DELETE\"",
    "\"DISTINCT\"",
    "\"DO\"",
    "\"DOUBLE\"",
    "\"DROP\"",
    "\"ELSE\"",
    "\"ELSEIF\"",
    "\"END\"",
    "\"ESCAPE\"",
    "\"EXISTS\"",
    "\"FETCH\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"IN\"",
    "\"IS\"",
    "\"INTO\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"INSERT\"",
    "\"REPLACE\"",
    "\"INTEGER\"",
    "\"INT\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"NATURAL\"",
    "\"CROSS\"",
    "\"LIKE\"",
    "\"LOCK\"",
    "\"LOOP\"",
    "\"CREATE\"",
    "\"NOT\"",
    "\"!\"",
    "\"NULL\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OF\"",
    "\"ON\"",
    "\"NOWAIT\"",
    "\"ONLY\"",
    "\"OR\"",
    "\"||\"",
    "\"ORDER\"",
    "\"OUTER\"",
    "\"QUERYNO\"",
    "\"OPTIMIZE\"",
    "\"READ\"",
    "\"REAL\"",
    "\"OPTION\"",
    "\"OFFSET\"",
    "\"EXPLAIN\"",
    "\"EXTENDED\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"XA\"",
    "\"SOME\"",
    "\"TABLE\"",
    "<K_SHOW>",
    "\"MOD\"",
    "\"DIV\"",
    "\"THEN\"",
    "\"TO\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UPDATE\"",
    "\"USE\"",
    "\"USING\"",
    "\"VALUES\"",
    "\"VARCHAR2\"",
    "\"VARCHAR\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WHILE\"",
    "\"WITH\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"LIMIT\"",
    "\"RIGHT\"",
    "\"INTERVAL\"",
    "\"YEAR\"",
    "\"MICROSECOND\"",
    "\"SECOND\"",
    "\"DAY\"",
    "\"MINUTE\"",
    "\"MONTH\"",
    "\"HOUR\"",
    "\"COMMIT\"",
    "\"BEGIN\"",
    "\"ROLLBACK\"",
    "\"desc\"",
    "\"asc\"",
    "\"IGNORE INDEX\"",
    "\"FORCE INDEX\"",
    "\"TRANSACTION ISOLATION LEVEL\"",
    "\"DUPLICATE\"",
    "\"KEY\"",
    "\"KEYS\"",
    "\"START TRANSACTION\"",
    "\"SESSION\"",
    "\"READ COMMITTED\"",
    "\"READ UNCOMMITTED\"",
    "\"REPEATABLE READ\"",
    "\"SERIALIZABLE\"",
    "\"CLIENT CHARSET\"",
    "<K_SHOW_FULL_TABLES>",
    "\"OPEN TABLES\"",
    "\"CREATE PROCEDURE\"",
    "<K_SHOW_CREATE_DATABASE>",
    "<K_SHOW_FULL_COLUMNS>",
    "\"TABLE STATUS\"",
    "\"VARIABLES\"",
    "\"GRANTS FOR\"",
    "\"TRIGGERS\"",
    "\"PROCEDURE\"",
    "\"EVENTS\"",
    "\"CALL\"",
    "\"CHARACTER SET\"",
    "\"IF NOT EXISTS\"",
    "\"IF EXISTS\"",
    "\"PRIMARY\"",
    "\"TRUNCATE\"",
    "\"VIEW\"",
    "<K_DATABASE>",
    "\"SEQUENCE\"",
    "\"TRIGGER \"",
    "<K_FUNCTION>",
    "<K_TEMPORARY>",
    "\"GLOBAL\"",
    "\"LOCAL\"",
    "\"RENAME\"",
    "\"ALTER\"",
    "\"IGNORE\"",
    "\"HELP\"",
    "\"DISTINCTROW\"",
    "\"HIGH_PRIORITY\"",
    "\"STRAIGHT_JOIN\"",
    "\"SQL_SMALL_RESULT\"",
    "\"SQL_BIG_RESULT\"",
    "\"SQL_BUFFER_RESULT\"",
    "\"SQL_CACHE\"",
    "\"SQL_NO_CACHE\"",
    "\"SQL_CALC_FOUND_ROWS\"",
    "\"ACCESSIBLE\"",
    "\"BEFORE\"",
    "\"BINARY\"",
    "\"COLUMN\"",
    "\"CONTINUE\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"DAY_MICROSECOND\"",
    "\"DEFAULT\"",
    "\"EACH\"",
    "\"ENCLOSED\"",
    "\"EXIT\"",
    "\"FLOAT8\"",
    "\"FOREIGN\"",
    "\"GRANT\"",
    "\"HOUR_SECOND\"",
    "\"INT2\"",
    "\"INT8\"",
    "\"KILL\"",
    "\"LINEAR\"",
    "\"LOCALTIME\"",
    "\"LONG\"",
    "\"MATCH\"",
    "\"MEDIUMINT\"",
    "\"MINUTE_MICROSECOND\"",
    "\"MODIFIES\"",
    "\"NO_WRITE_TO_BINLOG\"",
    "\"OPTIONALLY\"",
    "\"OUT\"",
    "\"PRECISION\"",
    "\"PURGE\"",
    "\"READS\"",
    "\"REFERENCES\"",
    "\"REQUIRE\"",
    "\"RETURN\"",
    "\"RLIKE\"",
    "\"SECOND_MICROSECOND\"",
    "\"SEPARATOR\"",
    "\"SIGNAL\"",
    "\"SPECIFIC\"",
    "\"SQLSTATE\"",
    "\"STARTING\"",
    "\"TERMINATED\"",
    "\"TINYINT\"",
    "\"TRAILING\"",
    "\"UNDO\"",
    "\"UNLOCK\"",
    "\"USAGE\"",
    "\"UTC_DATE\"",
    "\"VARCHARACTER\"",
    "\"WRITE\"",
    "\"ZEROFILL\"",
    "\"ADD\"",
    "\"ANALYZE\"",
    "\"BLOB\"",
    "\"CHANGE\"",
    "\"CHECK\"",
    "\"CONDITION\"",
    "\"CONVERT\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_USER\"",
    "\"DATABASES\"",
    "\"DAY_MINUTE\"",
    "\"DELAYED\"",
    "\"ESCAPED\"",
    "\"HOUR_MICROSECOND\"",
    "\"IF\"",
    "\"INOUT\"",
    "\"INT3\"",
    "\"LEADING\"",
    "\"LINES\"",
    "\"LOCALTIMESTAMP\"",
    "\"LONGBLOB\"",
    "\"LOW_PRIORITY\"",
    "\"MAXVALUE\"",
    "\"MEDIUMTEXT\"",
    "\"MINUTE_SECOND\"",
    "\"RANGE\"",
    "\"READ_WRITE\"",
    "\"REGEXP\"",
    "\"REPEAT\"",
    "\"RESIGNAL\"",
    "\"REVOKE\"",
    "\"SMALLINT\"",
    "\"SQL\"",
    "\"SQLWARNING\"",
    "\"TINYTEXT\"",
    "\"UNSIGNED\"",
    "\"UTC_TIME\"",
    "\"VARBINARY\"",
    "\"VARYING\"",
    "\"XOR\"",
    "\"ASENSITIVE\"",
    "\"BIGINT\"",
    "\"BOTH\"",
    "\"CASCADE\"",
    "\"COLLATE\"",
    "\"CONSTRAINT\"",
    "\"CURRENT_TIME\"",
    "\"CURSOR\"",
    "\"DAY_HOUR\"",
    "\"DAY_SECOND\"",
    "\"DECLARE\"",
    "\"DETERMINISTIC\"",
    "\"DUAL\"",
    "\"FLOAT4\"",
    "\"FORCE\"",
    "\"FULLTEXT\"",
    "\"HOUR_MINUTE\"",
    "\"INFILE\"",
    "\"INSENSITIVE\"",
    "\"INT1\"",
    "\"INT4\"",
    "\"ITERATE\"",
    "\"LEAVE\"",
    "\"LOAD\"",
    "\"LONGTEXT\"",
    "\"MASTER_SSL_VERIFY_SERVER_CERT\"",
    "\"MEDIUMBLOB\"",
    "\"MIDDLEINT\"",
    "\"OUTFILE\"",
    "\"RELEASE\"",
    "\"RESTRICT\"",
    "\"SCHEMAS\"",
    "\"SENSITIVE\"",
    "\"SPATIAL\"",
    "\"SQLEXCEPTION\"",
    "\"SSL\"",
    "\"TINYBLOB\"",
    "\"UTC_TIMESTAMP\"",
    "\"YEAR_MONTH\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<STRING_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<S_COMMA_IDENTIFIER>",
    "<S_PARAMETER_MARKER>",
    "\"=\"",
    "\"/*!\"",
    "\"/*\"",
    "\"#\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"*/\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\".\"",
    "\"START WITH\"",
    "\"INCREMENT BY\"",
    "\"`\"",
    "\"!=\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"*\"",
    "\".*\"",
    "\"+\"",
    "\"-\"",
    "\"|\"",
    "\"&\"",
    "\"/\"",
    "\"%\"",
    "\"DATE\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
    "\"USE INDEX\"",
  };

}
